controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - boom_link_JOINT_0

arm_controller:
  ros__parameters:
    joints:
      - boom_link_JOINT_0
    
    command_interfaces:
      - effort
    
    state_interfaces:
      - position
      - velocity
    
    gains:
      boom_link_JOINT_0:
        p: 100.0
        i: 0.0
        d: 5.0